const musicas = [

{
    id:1,
    codigo:"001",
    nome:"LET IT BE",
    artista:"BEATLES",
    ano:1970,
    arquivo:"audio/001.mp3",
},

{
    id:2,
    codigo:"002",
    nome:"LE FREAK",
    artista:"CHIC",
    ano:1978,
    arquivo:"audio/002.mp3",
},

{
    id:3,
    codigo:"003",
    nome:"Killing Me Softly With His Song",
    artista:"ROBERTA FLACK",
    ano:1973,
    arquivo:"audio/003.mp3",
},

{
    id:4,
    codigo:"004",
    nome:"Isn't She Lovely",
    artista:"Stevie Wonder",
    ano:1976,
    arquivo:"audio/004.mp3",
},

{
    id:5,
    codigo:"005",
    nome:"INFINITA HIGHWAY",
    artista:"ENGENHEIROS DO HAWAII",
    ano:2004,
    arquivo:"audio/005.mp3",
},

{
    id:6,
    codigo:"006",
    nome:"IMAGINE",
    artista:"JOHN LENNON",
    ano:1971,
    arquivo:"audio/006.mp3",
},

{
    id:7,
    codigo:"007",
    nome:"I'm Coming Out",
    artista:"DIANA ROSS",
    ano:1980,
    arquivo:"audio/007.mp3",
},

{
    id:8,
    codigo:"008",
    nome:"Have You Ever Seen The Rain",
    artista:"Creedence Clearwater Revival",
    ano:1973,
    arquivo:"audio/008.mp3",
},

{
    id:9,
    codigo:"009",
    nome:"Gonna Make You Sweat",
    artista:"C+C Music Factory",
    ano:1991,
    arquivo:"audio/009.mp3",
},

{
    id:10,
    codigo:"010",
    nome:"Footloose",
    artista:"Kenny Loggins",
    ano:1984,
    arquivo:"audio/010.mp3",
},

{
    id:11,
    codigo:"011",
    nome:"Get Down On It",
    artista:"Kool & The Gang",
    ano:1981,
    arquivo:"audio/011.mp3",
},

{
    id:12,
    codigo:"012",
    nome:"NUMB",
    artista:"LINKIN PARK",
    ano:2003,
    arquivo:"audio/012.mp3",
},

{
    id:13,
    codigo:"013",
    nome:"Play That Funky Music",
    artista:"Wild Cherry",
    ano:1976,
    arquivo:"audio/013.mp3",
},

{
    id:14,
    codigo:"014",
    nome:"A PAZ",
    artista:"GILBERTO GIL",
    ano:1994,
    arquivo:"audio/014.mp3",
},

{
    id:15,
    codigo:"015",
    nome:"APENAS MAIS UMA DE AMOR",
    artista:"LULU SANTOS",
    ano:2000,
    arquivo:"audio/015.mp3",
},

{
    id:16,
    codigo:"016",
    nome:"AS QUATRO ESTAÇÕES",
    artista:"SANDY & JUNIOR",
    ano:2007,
    arquivo:"audio/016.mp3",
},

{
    id:17,
    codigo:"017",
    nome:"BEAT IT",
    artista:"MICHAEL JACKSON",
    ano:1982,
    arquivo:"audio/017.mp3",
},

{
    id:18,
    codigo:"018",
    nome:"If You Leave Me Now",
    artista:"CHICAGO",
    ano:1976,
    arquivo:"audio/018.mp3",
},

{
    id:19,
    codigo:"019",
    nome:"Eye of the Tiger",
    artista:"SURVIVOR",
    ano:1982,
    arquivo:"audio/019.mp3",
},

{
    id:20,
    codigo:"020",
    nome:"All Out Of Love",
    artista:"Air Supply",
    ano:1980,
    arquivo:"audio/020.mp3",
},

{
    id:21,
    codigo:"021",
    nome:"Celebration",
    artista:"Kool & The Gang",
    ano:1980,
    arquivo:"audio/021.mp3",
},

{
    id:22,
    codigo:"022",
    nome:"Funkytown",
    artista:"Lipps Inc.",
    ano:1980,
    arquivo:"audio/022.mp3",
},

{
    id:23,
    codigo:"023",
    nome:"Livin' On A Prayer",
    artista:"Bon Jovi",
    ano:1986,
    arquivo:"audio/023.mp3",
},

{
    id:24,
    codigo:"024",
    nome:"Malandragem",
    artista:"Cassia Eller",
    ano:1994,
    arquivo:"audio/024.mp3",
},

{
    id:25,
    codigo:"025",
    nome:"Me Chama",
    artista:"Lobão",
    ano:2000,
    arquivo:"audio/025.mp3",
},

{
    id:26,
    codigo:"026",
    nome:"Os Cegos do Castelo",
    artista:"Nando Reis",
    ano:1997,
    arquivo:"audio/026.mp3",
},

{
    id:27,
    codigo:"027",
    nome:"Pescador de Ilusões",
    artista:"O Rappa",
    ano:2005,
    arquivo:"audio/027.mp3",
},

{
    id:28,
    codigo:"028",
    nome:"Primeiros Erros",
    artista:"Capital Inicial",
    ano:2000,
    arquivo:"audio/028.mp3",
},

{
    id:29,
    codigo:"029",
    nome:"Rocket Man",
    artista:"Elton John",
    ano:1972,
    arquivo:"audio/029.mp3",
},

{
    id:30,
    codigo:"030",
    nome:"Sailing",
    artista:"Christopher Cross",
    ano:1980,
    arquivo:"audio/030.mp3",
},

{
    id:31,
    codigo:"031",
    nome:"September",
    artista:"Earth, Wind & Fire",
    ano:1978,
    arquivo:"audio/031.mp3",
},

{
    id:32,
    codigo:"032",
    nome:"Starman",
    artista:"David Bowie",
    ano:1972,
    arquivo:"audio/032.mp3",
},

{
    id:33,
    codigo:"033",
    nome:"Stayin' Alive",
    artista:"Bee Gees",
    ano:1977,
    arquivo:"audio/033.mp3",
},

{
    id:34,
    codigo:"034",
    nome:"Take On Me",
    artista:"a-ha",
    ano:1985,
    arquivo:"audio/034.mp3",
},

{
    id:35,
    codigo:"035",
    nome:"I Wanna Dance With Somebody",
    artista:"Whitney Houston",
    ano:1987,
    arquivo:"audio/035.mp3",
},

{
    id:36,
    codigo:"036",
    nome:"You Give Love a Bad Name",
    artista:"Bon Jovi",
    ano:1986,
    arquivo:"audio/036.mp3",
},

{
    id:37,
    codigo:"037",
    nome:"You Should Be Dancing",
    artista:"Bee Gees",
    ano:1976,
    arquivo:"audio/037.mp3",
},

{
    id: 38,
    codigo: "038",
    nome: "What's Up",
    artista: "4 Non Blondes",
    ano: 1993,
    arquivo: "audio/038.mp3",
},
{
    id: 39,
    codigo: "039",
    nome: "Ain't No Mountain High Enough",
    artista: "Marvin Gaye x Tammi Terrell",
    ano: 1967,
    arquivo: "audio/048-39.mp3",
},
{
    id: 40,
    codigo: "040",
    nome: "Anunciação",
    artista: "Alceu Valença",
    ano: 1983,
    arquivo: "audio/040.mp3",
},
{
    id: 41,
    codigo: "041",
    nome: "Árvore",
    artista: "Edson Gomes",
    ano: 1992,
    arquivo: "audio/046-41.mp3",
},
{
    id: 42,
    codigo: "042",
    nome: "Bilu, Bilu",
    artista: "Pablo",
    ano: 2014,
    arquivo: "audio/050-42.mp3",
},
{
    id: 43,
    codigo: "043",
    nome: "Black or White",
    artista: "Michael Jackson",
    ano: 1991,
    arquivo: "audio/051-43.mp3",
},
{
    id: 44,
    codigo: "044",
    nome: "Borboletas",
    artista: "Victor & Leo",
    ano: 2008,
    arquivo: "audio/052-44.mp3",
},
{
    id: 45,
    codigo: "045",
    nome: "Camelo",
    artista: "Edson Gomes",
    ano: 1997,
    arquivo: "audio/053-45.mp3",
},
{
    id: 46,
    codigo: "046",
    nome: "Exagerado",
    artista: "Cazuza",
    ano: 1985,
    arquivo: "audio/054-46.mp3",
},
{
    id: 47,
    codigo: "047",
    nome: "The Twist",
    artista: "Chubby Checker",
    ano: 1960,
    arquivo: "audio/055-47.mp3",
},
{
    id: 48,
    codigo: "048",
    nome: "Easy",
    artista: "Commodores",
    ano: 1977,
    arquivo: "audio/048.mp3",
},
{
    id: 49,
    codigo: "049",
    nome: "Como eu quero",
    artista: "Kid Abelha",
    ano: 1984,
    arquivo: "audio/040-49.mp3",
},
{
    id: 50,
    codigo: "050",
    nome: "Dancing Queen",
    artista: "ABBA",
    ano: 1976,
    arquivo: "audio/041-50.mp3",
},
{
    id: 51,
    codigo: "051",
    nome: "Diga Sim pra Mim",
    artista: "Desejo de Menina",
    ano: 2008,
    arquivo: "audio/042-51.mp3",
},
{
    id: 52,
    codigo: "052",
    nome: "Do Lado de Cá",
    artista: "Chimarruts",
    ano: 2010,
    arquivo: "audio/043-52.mp3",
},
{
    id: 53,
    codigo: "053",
    nome: "Don't Matter",
    artista: "Akon",
    ano: 2007,
    arquivo: "audio/044-53.mp3",
},
{
    id: 54,
    codigo: "054",
    nome: "Coração",
    artista: "Dorgival Dantas",
    ano: 2005,
    arquivo: "audio/045-54.mp3",
},
{
    id: 55,
    codigo: "055",
    nome: "É o Amor",
    artista: "Zezé Di Camargo & Luciano",
    ano: 1991,
    arquivo: "audio/047-55.mp3",
},

{
    id: 56,
    codigo: "056",
    nome: "ENDOIDECEU MEU CORAÇÃO",
    artista: "João Gomes",
    ano: null,
    arquivo: "audio/056.mp3",
},
{
    id: 57,
    codigo: "057",
    nome: "Esse Cara Sou Eu",
    artista: "Roberto Carlos",
    ano: 2012,
    arquivo: "audio/057.mp3",
},
{
    id: 58,
    codigo: "058",
    nome: "Eu Só Quero um Xodó",
    artista: "Dominguinhos",
    ano: null,
    arquivo: "audio/058.mp3",
},
{
    id: 59,
    codigo: "059",
    nome: "Eu Tenho Medo",
    artista: "Zé Vaqueiro",
    ano: 2020,
    arquivo: "audio/059.mp3",
},
{
    id: 60,
    codigo: "060",
    nome: "Evidências",
    artista: "Chitãozinho & Xororó",
    ano: 1990,
    arquivo: "audio/060.mp3",
},
{
    id: 61,
    codigo: "061",
    nome: "Fico Assim Sem Você",
    artista: "Claudinho & Buchecha",
    ano: null,
    arquivo: "audio/061.mp3",
},
{
    id: 62,
    codigo: "062",
    nome: "Dreams",
    artista: "Fleetwood Mac",
    ano: 1977,
    arquivo: "audio/062.mp3",
},
{
    id: 63,
    codigo: "063",
    nome: "Garota Nota 100",
    artista: "MC Marcinho",
    ano: 1998,
    arquivo: "audio/063.mp3",
},
{
    id: 64,
    codigo: "064",
    nome: "Give It Up",
    artista: "KC and the Sunshine Band",
    ano: null,
    arquivo: "audio/064.mp3",
},
{
    id: 65,
    codigo: "065",
    nome: "Gostava Tanto De Você",
    artista: "Tim Maia",
    ano: 1973,
    arquivo: "audio/065.mp3",
},
{
    id: 66,
    codigo: "066",
    nome: "Flashdance What A Feeling",
    artista: "Irene Cara",
    ano: null,
    arquivo: "audio/066.mp3",
},
{
    id: 67,
    codigo: "067",
    nome: "Is This Love",
    artista: "Bob Marley",
    ano: 1978,
    arquivo: "audio/067.mp3",
},
{
    id: 68,
    codigo: "068",
    nome: "Please Don't Go",
    artista: "KC & The Sunshine Band",
    ano: null,
    arquivo: "audio/068.mp3",
},
{
    id: 69,
    codigo: "069",
    nome: "La Belle De Jour",
    artista: "Alceu Valença",
    ano: 1992,
    arquivo: "audio/049-69.mp3",
},
{
    id: 70,
    codigo: "070",
    nome: "Tempo perdido",
    artista: "Legião Urbana",
    ano: 1986,
    arquivo: "audio/070.mp3",
},
{
    id: 71,
    codigo: "071",
    nome: "Linda Bela",
    artista: "Elias Monkbel",
    ano: 2019,
    arquivo: "audio/071.mp3",
},
{
    id: 72,
    codigo: "072",
    nome: "Lonely",
    artista: "Akon",
    ano: null,
    arquivo: "audio/072.mp3",
},
{
    id: 73,
    codigo: "073",
    nome: "Mágica",
    artista: "Calcinha Preta",
    ano: 2004,
    arquivo: "audio/073.mp3",
},

{
    id: 74,
    codigo: "074",
    nome: "Malandrinha",
    artista: "Edson Gomes",
    ano: 1998,
    arquivo: "audio/074.mp3",
},
{
    id: 75,
    codigo: "075",
    nome: "Manchete dos Jornais",
    artista: "Calcinha Preta",
    ano: 2003,
    arquivo: "audio/075.mp3",
},
{
    id: 76,
    codigo: "076",
    nome: "Marrom Bombom",
    artista: "Os Morenos",
    ano: null,
    arquivo: "audio/076.mp3",
},
{
    id: 77,
    codigo: "077",
    nome: "Me Namora",
    artista: "Edu Ribeiro",
    ano: 2004,
    arquivo: "audio/077.mp3",
},
{
    id: 78,
    codigo: "078",
    nome: "Metamorfose Ambulante",
    artista: "Raul Seixas",
    ano: 1973,
    arquivo: "audio/078.mp3",
},
{
    id: 79,
    codigo: "079",
    nome: "Meu Erro",
    artista: "Os Paralamas Do Sucesso",
    ano: 1984,
    arquivo: "audio/079.mp3",
},
{
    id: 80,
    codigo: "080",
    nome: "Meu Mel",
    artista: "Zé Vaqueiro",
    ano: 2020,
    arquivo: "audio/080.mp3",
},
{
    id: 81,
    codigo: "081",
    nome: "Meu Pedaço de Pecado",
    artista: "João Gomes",
    ano: 2021,
    arquivo: "audio/081.mp3",
},
{
    id: 82,
    codigo: "082",
    nome: "Over My Shoulder",
    artista: "Mike + The Mechanics",
    ano: 1995,
    arquivo: "audio/082.mp3",
},
{
    id: 83,
    codigo: "083",
    nome: "Monalisa",
    artista: "Jorge Vercillo",
    ano: 2003,
    arquivo: "audio/083.mp3",
},
{
    id: 84,
    codigo: "084",
    nome: "Morango do Nordeste",
    artista: "Karametade",
    ano: 2000,
    arquivo: "audio/084.mp3",
},
{
    id: 85,
    codigo: "085",
    nome: "Morena Tropicana",
    artista: "Alceu Valença",
    ano: 1982,
    arquivo: "audio/085.mp3",
},
{
    id: 86,
    codigo: "086",
    nome: "Night Fever",
    artista: "Bee Gees",
    ano: 1978,
    arquivo: "audio/086.mp3",
},
{
    id: 87,
    codigo: "087",
    nome: "No Dia em Que Eu Saí de Casa",
    artista: "Zezé Di Camargo & Luciano",
    ano: 1995,
    arquivo: "audio/087.mp3",
},
{
    id: 88,
    codigo: "088",
    nome: "No Woman, No Cry",
    artista: "Bob Marley",
    ano: 1974,
    arquivo: "audio/088.mp3",
},
{
    id: 89,
    codigo: "089",
    nome: "O Astronauta de Marmore",
    artista: "Nenhum de Nós",
    ano: 1989,
    arquivo: "audio/089.mp3",
},
{
    id: 90,
    codigo: "090",
    nome: "O Descobridor Dos Sete Mares",
    artista: "Tim Maia",
    ano: 1983,
    arquivo: "audio/090.mp3",
},

{
    id: 91,
    codigo: "091",
    nome: "Oh Chuva",
    artista: "Planta E Raiz",
    ano: 2000,
    arquivo: "audio/091.mp3",
},

{
    id: 92,
    codigo: "092",
    nome: "Pássaro De Fogo",
    artista: "Paula Fernandes",
    ano: 2009,
    arquivo: "audio/094-92.mp3",
},
{
    id: 93,
    codigo: "093",
    nome: "Perdido De Amor",
    artista: "Edson Gomes",
    ano: 1997,
    arquivo: "audio/092-93.mp3",
},
{
    id: 94,
    codigo: "094",
    nome: "Perfume",
    artista: "Belo",
    ano: 2008,
    arquivo: "audio/093-94.mp3",
},
{
    id: 95,
    codigo: "095",
    nome: "Quero Te Encontrar",
    artista: "Claudinho & Buchecha",
    ano: 1997,
    arquivo: "audio/095.mp3",
},
{
    id: 96,
    codigo: "096",
    nome: "Right Here Waiting",
    artista: "Richard Marx",
    ano: 1989,
    arquivo: "audio/096.mp3",
},
{
    id: 97,
    codigo: "097",
    nome: "Sinônimos",
    artista: "Chitãozinho & Xororó",
    ano: 2004,
    arquivo: "audio/097.mp3",
},
{
    id: 98,
    codigo: "098",
    nome: "I'm a Believer",
    artista: "Smash Mouth",
    ano: 2001,
    arquivo: "audio/098.mp3",
},
{
    id: 99,
    codigo: "099",
    nome: "Só Love",
    artista: "Claudinho & Buchecha",
    ano: 1998,
    arquivo: "audio/099.mp3",
},
{
    id: 100,
    codigo: "100",
    nome: "Tá Vendo Aquela Lua",
    artista: "Exalta Samba",
    ano: 2010,
    arquivo: "audio/106-100.mp3",
},
{
    id: 101,
    codigo: "101",
    nome: "Tempos modernos",
    artista: "Lulu Santos",
    ano: 1982,
    arquivo: "audio/100-101.mp3",
},
{
    id: 102,
    codigo: "102",
    nome: "Best of My Love",
    artista: "The Emotions",
    ano: 1977,
    arquivo: "audio/101-102.mp3",
},
{
    id: 103,
    codigo: "103",
    nome: "I Don't Wanna Lose You",
    artista: "Tina Turner",
    ano: 1989,
    arquivo: "audio/102-103.mp3",
},
{
    id: 104,
    codigo: "104",
    nome: "Toma Conta De Mim",
    artista: "Limão com Mel",
    ano: 2002,
    arquivo: "audio/103-104.mp3",
},
{
    id: 105,
    codigo: "105",
    nome: "Treasure",
    artista: "Bruno Mars",
    ano: 2012,
    arquivo: "audio/104-105.mp3",
},
{
    id: 106,
    codigo: "106",
    nome: "True Love",
    artista: "SOJA",
    ano: 2006,
    arquivo: "audio/105-106.mp3",
},
{
    id: 107,
    codigo: "107",
    nome: "Vou Deixar",
    artista: "Skank",
    ano: 2003,
    arquivo: "audio/107.mp3",
},
{
    id: 108,
    codigo: "108",
    nome: "Wonderwall",
    artista: "Oasis",
    ano: 1995,
    arquivo: "audio/108.mp3",
},
{
    id: 109,
    codigo: "109",
    nome: "Xote dos Milagres",
    artista: "Falamansa",
    ano: 2000,
    arquivo: "audio/109.mp3",
},
{
    id: 110,
    codigo: "110",
    nome: "Deixe-me ir",
    artista: "1Kilo",
    ano: 2017,
    arquivo: "audio/110.mp3",
},
{
    id: 111,
    codigo: "111",
    nome: "Anna Júlia",
    artista: "LOS HERMANOS",
    ano: 1999,
    arquivo: "audio/111.mp3",
},
{
    id: 112,
    codigo: "112",
    nome: "Apenas Mais Uma De Amor",
    artista: "Lulu Santos",
    ano: 1992,
    arquivo: "audio/112.mp3",
},
{
    id: 113,
    codigo: "113",
    nome: "Burguesinha",
    artista: "Seu Jorge",
    ano: 2007,
    arquivo: "audio/113.mp3",
},
{
    id: 114,
    codigo: "114",
    nome: "Céu Azul",
    artista: "Charlie Brown Jr",
    ano: 2011,
    arquivo: "audio/114.mp3",
},
{
    id: 115,
    codigo: "115",
    nome: "Coisas Que Eu Sei",
    artista: "Danni Carlos",
    ano: 2007,
    arquivo: "audio/115.mp3",
},
{
    id: 116,
    codigo: "116",
    nome: "Dias De Luta, Dias De Gloria",
    artista: "Charlie Brown Jr.",
    ano: 2005,
    arquivo: "audio/116.mp3",
},
{
    id: 117,
    codigo: "117",
    nome: "Sina",
    artista: "Djavan",
    ano: 1982,
    arquivo: "audio/117.mp3",
},
{
    id: 118,
    codigo: "118",
    nome: "Equalize",
    artista: "Pitty",
    ano: 2003,
    arquivo: "audio/118.mp3",
},
{
    id: 119,
    codigo: "119",
    nome: "Eu Amo Você",
    artista: "Tim Maia",
    ano: 1970,
    arquivo: "audio/119.mp3",
},
{
    id: 120,
    codigo: "120",
    nome: "Eu Sei",
    artista: "Papas Da Língua",
    ano: 2002,
    arquivo: "audio/120.mp3",
},
{
    id: 121,
    codigo: "121",
    nome: "Borbulhas de Amor",
    artista: "Fagner",
    ano: 1991,
    arquivo: "audio/121.mp3",
},
{
    id: 122,
    codigo: "122",
    nome: "Felicidade",
    artista: "Seu Jorge",
    ano: 2015,
    arquivo: "audio/122.mp3",
},
{
    id: 123,
    codigo: "123",
    nome: "João e Maria",
    artista: "Chico Buarque",
    ano: 1977,
    arquivo: "audio/123.mp3",
},
{
    id: 124,
    codigo: "124",
    nome: "Lágrimas E Chuva",
    artista: "Kid Abelha",
    ano: 1985,
    arquivo: "audio/124.mp3",
},
{
    id: 125,
    codigo: "125",
    nome: "Lanterna Dos Afogados",
    artista: "Os Paralamas Do Sucesso",
    ano: 1989,
    arquivo: "audio/125.mp3",
},
{
    id: 126,
    codigo: "126",
    nome: "Linha do Equador",
    artista: "Djavan",
    ano: 1992,
    arquivo: "audio/126.mp3",
},
{
    id: 127,
    codigo: "127",
    nome: "Na Linha do Tempo",
    artista: "Victor & Leo",
    ano: 2013,
    arquivo: "audio/127.mp3",
},
{
    id: 128,
    codigo: "128",
    nome: "Naquela Mesa",
    artista: "Nelson Gonçalves",
    ano: 1972,
    arquivo: "audio/128.mp3",
},
{
    id: 129,
    codigo: "129",
    nome: "Nem um Dia",
    artista: "Djavan",
    ano: 1996,
    arquivo: "audio/129.mp3",
},
{
    id: 130,
    codigo: "130",
    nome: "Pela Luz dos Olhos Teus",
    artista: "Miucha",
    ano: 1977,
    arquivo: "audio/130.mp3",
},
{
    id: 131,
    codigo: "131",
    nome: "Vagalumes (part. Ivo Mozart)",
    artista: "Pollo",
    ano: 2012,
    arquivo: "audio/131.mp3",
},
{
    id: 132,
    codigo: "132",
    nome: "Por Você (Acústica)",
    artista: "Barão Vermelho",
    ano: 1998,
    arquivo: "audio/132.mp3",
},
{
    id: 133,
    codigo: "133",
    nome: "Sem Radar",
    artista: "LS Jack",
    ano: 2003,
    arquivo: "audio/133.mp3",
},
{
    id: 134,
    codigo: "134",
    nome: "SENHOR DO TEMPO",
    artista: "Charlie Brown Jr.",
    ano: 2005,
    arquivo: "audio/134.mp3",
},
{
    id: 135,
    codigo: "135",
    nome: "Será que é amor",
    artista: "Arlindo Cruz",
    ano: 2003,
    arquivo: "audio/135.mp3",
},
{
    id: 136,
    codigo: "136",
    nome: "Acima do Sol",
    artista: "Skank",
    ano: 2001,
    arquivo: "audio/136.mp3",
},
{
    id: 137,
    codigo: "137",
    nome: "Só Hoje",
    artista: "Jota Quest",
    ano: 2002,
    arquivo: "audio/137.mp3",
},
{
    id: 138,
    codigo: "138",
    nome: "Só Os Loucos Sabem",
    artista: "Charlie Brown Jr.",
    ano: 2009,
    arquivo: "audio/138.mp3",
},
{
    id: 139,
    codigo: "139",
    nome: "Enquanto Houver Sol",
    artista: "Titãs",
    ano: 2003,
    arquivo: "audio/139.mp3",
},
{
    id: 140,
    codigo: "140",
    nome: "Tive Razão",
    artista: "Seu Jorge",
    ano: 2004,
    arquivo: "audio/140.mp3",
},
{
    id: 141,
    codigo: "141",
    nome: "Várias Queixas",
    artista: "Gilsons",
    ano: 2019,
    arquivo: "audio/141.mp3",
},
{
    id: 142,
    codigo: "142",
    nome: "Velha Infância",
    artista: "Tribalista",
    ano: 2002,
    arquivo: "audio/142.mp3",
}

];
